# Generated by Django 4.0.4 on 2022-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
