# Generated by Django 4.0.4 on 2022-06-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
